### ISSUE TITLE
Shortcut for fullscreen never working and other bugs

### ISSUE THREAD

**Issue by stefonarch** [lxqt/screengrab#291] opened 2022-03-26 20:30 UTC
Only 2 of the 3 shortcuts are working: window and area. And shortcut for fullscreen is the one which results in "window".
Shortcuts with ctrl never work in those 3 settings, and with meta it's not working too:
![screengrab](https://user-images.githubusercontent.com/10681413/160255841-6c731277-08da-4def-9b0c-2ec741be7e31.png)

##### Steps to Reproduce (for bugs)

1. Open preferences, add shortcuts: F for fullscreen, W for window, A for area and save it.
2. Press A → area will be set if it's not set already
3. Press W → nothing  happens
4. Press F → window instead of fullscreen is set.

##### System Information

* Distribution & Version: latest git, LXQt 1.0.0 too

**Comment by tsujan** [comment] 2022-03-26 21:47
Confirming the existence of the bug.

In practice, those shortcuts aren't needed though. Global shortcuts can be made for `screengrab -f`, `screengrab -a`,.... Personally, I use `PrtSc` and `Alt+PrtSc` for fullscreen and window screenshots.

**Comment by tsujan** [comment] 2022-03-26 22:06
BTW, the problem with Meta is a known Qt bug. A report has been made at https://bugreports.qt.io/browse/QTBUG-62102 but, contrary to its title, it isn't limited to Wayland. I worked around it (partially) everywhere I added a shortcut editor.

**Comment by stefonarch** [comment] 2022-03-27 06:24
> In practice, those shortcuts aren't needed though

I agree partially, I stumpled upon that by case. I use "last selected area" width delay mostly, and use the dropdown to change - here they can be useful,` screengrab -*` shortcuts won't work in single instance mode when it's already open.

**Comment by tsujan** [comment] 2022-03-27 08:41
> screengrab -* shortcuts won't work in single instance mode when it's already open.

They do here. I don't close the single-instance window to take another screenshot with PrtSc/Alt+PrtSc.

**Comment by stefonarch** [comment] 2022-03-27 09:04
With window open or minimized int tray it tries to open a second instance (opens space in systray shortly)
```
$ screengrab -a
QLocalSocket::connectToServer: Connection refused

```
Same goes here for general shortcut (ctrl+stamp), it doesn't work when already open.

**Comment by tsujan** [comment] 2022-03-27 09:14
Here, in the single-instance mode, it doesn't open a second window but shows the new screenshot in the same window, replacing the previous screenshot.

**Comment by stefonarch** [comment] 2022-03-27 10:14
Hm, strange, tested on the PC and there it works as by you, on the laptop not, and settings are the same. Difference is xfwm4 >< kwin

**Comment by tsujan** [comment] 2022-03-27 17:33
Probably a bug in xfwm4. I'm not sure because I haven't checked the code yet.

**Comment by stefonarch** [comment] 2022-03-27 18:03
No, it's the other way round: with kwin it doesn't work. Will try a xfwm4 session on the laptop.

**Comment by tsujan** [comment] 2022-03-27 18:19
LOL!

So, there should be another factor because I have KWin and it works fine.

BTW, let's not forget that the main bug you reported was about another problem.

**Comment by tsujan** [comment] 2022-03-29 13:28
OK, I took a look at the code. It supports two sets of shortcuts, whose difference from each other is just in their names: local and global shortcuts. The local shortcuts are assigned to the GUI actions, while the "global" shortcuts (for fullscreen, active window and screen area) aren't assigned to anything.

I think the "global" shortcuts were supposed to be really global at some point but, since except for apps like panel and WM, most apps shouldn't have global shortcuts (because they could interfere with the global shortcuts of DE), they're left unused.

IMO, "global" shortcuts should be removed from the Shortcuts page and the really global shortcuts of the DE should be used instead of them. "Global" shortcuts can make the user think that he could use them when the app is minimized to tray (while he can't). Any objection to their removal?

**Comment by stefonarch** [comment] 2022-03-29 14:37
> Any objection to their removal?

Not from my side.

**Comment by tsujan** [comment] 2022-03-29 15:15
OK. I'll do it.

The shortcut code is a mess. It also has a bug:

 1. Double click an existing shortcut.
 2. Do nothing other than selecting another existing shortcut.

Then Screengrab shows a dialog that says the shortcut is in use and clears it.

I'll only remove global shortcut from the GUI (not from the code) and fix the bug. Cleaning the current mess is beyond my free time for now.

**Comment by tsujan** [comment] 2022-03-29 18:02
https://github.com/lxqt/screengrab/pull/293 is a temporary patch; the bad codes aren't replaced by it. Later — maybe after LXQt 1.1.0 — I'll add a real shortcuts editor, like that of lximage-qt.

**Closed** 2022-03-29 18:30 UTC

**Comment by tsujan** [comment] 2022-03-29 18:41
Did you find out why you can't use `screengrab -a` while the single-instance mode is running (Options → Advanced → Allow multiple instances → Unchecked)? Test this with the single-instance mode:

 1. Quit screengrab.
 2. Remove `/tmp/2.3.0` if it exists.
 3. Run screengrab.
 4. Try `screengrab -a`.

I guess the socket file had remained there in your case. Also, see https://github.com/lxqt/screengrab/issues/184

BTW, `2.3.0` is a bad name for that socket file.

Correcting screengrab's code needs a lot of time, which I haven't found yet. Maybe after LXQt 1.1.0....

**Comment by tsujan** [comment] 2022-03-29 18:50
Oh, because there are also two temporary files besides `/tmp/2.3.0`, you might need to reboot to get rid of them safely, provided that the above test fails. _(Never remove temporary files if you don't know to which app they belong, or if the app is running.)_

**Comment by stefonarch** [comment] 2022-03-29 20:22
I wonder instead why I don't have that issue anymore, noticed it before while testing shortcuts. It works well now. Lately my laptop is possessed by some daemon ;)

**Comment by tsujan** [comment] 2022-03-29 20:38
> I wonder instead why I don't have that issue anymore

Because the temp files were removed somehow, after a reboot or by other means.

Screengrab uses `QSharedMemory` to have a single instance, but `QSharedMemory` isn't reliable for that purpose (I had a bad experience with it years ago and, because of what you saw, I think its bug isn't fixed yet). Later, we should switch to either `QLockFile` or `QDBusConnection`.

However, https://github.com/lxqt/screengrab/issues/184 isn't caused by `QSharedMemory` but by Screengrab's code itself.

**Comment by stefonarch** [comment] 2022-03-30 06:18
> Because the temp files were removed somehow, after a reboot or by other means.

So it will return, theoretically. Looks like fixing https://github.com/lxqt/screengrab/issues/184 will solve. Anyway, it's not something real annoying.

**Comment by tsujan** [comment] 2022-03-30 11:42
> theoretically. Looks like fixing https://github.com/lxqt/screengrab/issues/184 will solve

Yes.
