### ISSUE TITLE
Add warning/error when screengrab is runned in a wayland session

### ISSUE THREAD

**Issue by iamthesenate1** [lxqt/screengrab#264] opened 2021-07-01 13:04 UTC
##### Context

As wayland is not supported and when trying to make a screenshot the app freezes for a while only to have an empty output , I think that an error/warning about this should be shown to users on the wayland session.

**Comment by tsujan** [comment] 2021-07-01 13:10
Almost a duplicate of https://github.com/lxqt/screengrab/issues/204.

The problem is not even in Qt but in the poor structure of Wayland.

**Closed by tsujan** 2021-07-01 13:10 UTC

**Comment by iamthesenate1** [comment] 2021-07-01 13:19
Yes. I know about #204. I suggested this so that people on wayland that don't know about it are informed.
Also, IMO this should be an error so that screengrab wouldn't even run, because of the annoying freeze before the user eventually finds out that it didn't work.

**Comment by tsujan** [comment] 2021-07-01 13:33
Wayland has more than one problem. For example, Qt's drag-and-drop can cause freeze or crash in apps, Qt menus/tooltips may be opened in wrong places, etc.. Some say that problems are in Qt, some say that Wayland doesn't allow a unified approach in all tookkits (which is true), and so on. Anyway, It's not our job to tell users about those problems.

**Comment by iamthesenate1** [comment] 2021-07-01 13:48
Yes. What I meant was basiclly not allowing screengrab to run on wayland (because it doesn't work anyway as you mentioned). The error wouldn't have to be long, just something simple, like "Screengrab doesn't work on Wayland, hence it will close now."

**Comment by mihaiolteanu** [comment] 2021-11-16 12:24
...just came here trying to figure out why screengrab doesn't work for me while using wayland...

**Comment by gdarko** [comment] 2022-09-03 09:47
I hope they fix wayland once and for all, it is terrible and breaks applications. I have the same problems on my app, can't grab screen. No permission system. Terrible.

**Comment by tsujan** [comment] 2022-09-03 13:55
> I hope they fix wayland once and for all

Wayland itself doesn't cause those problems; the lack of standards does. Even two Wayland compositors that are based on `wlroots` may not be compatible with each other.

**Comment by stefonarch** [comment] 2025-04-22 18:03
https://github.com/lxqt/screengrab/pull/400
