### ISSUE TITLE
type is not respected when pressing the print-key

### ISSUE THREAD

**Issue by ralf3u** [lxqt/screengrab#290] opened 2022-03-14 07:09 UTC
steps to reproduce
1: open ScreenGrab
2: select as type in the pull-down-menu "screen area" (or something like this, because I don't use the English version)
3: close ScreenGrab
4: open ScreenGrab
5: draw a rectangle with the mouse with pressed left-key of the mouse
6: press the enter-key of the keyboard
7: select in ScreenGrab as type in the pull-down-menu: "full-screen" (or something like this, because I don't use the English version)
8: press the print-key on the keyboard

result
I'm asked to draw a rectangle

expectation
a screenshot of the full-screen should be made because full-screen is selected

remark
- I know that I could use Ctrl+N, but I think the print-key should work also correctly
- the type is respected when pressing the print-key, but after a restart of ScreenGrab

my ScreenGrab 2.2.0 is old (in Lubuntu 21.10); but I still don’t know how to install the latest version;
if the issue does not appear in SreenGrab 2.3.0 any more, then I’m sorry for this report

**Comment by tsujan** [comment] 2022-03-14 07:24
Not reproducible.

> press the print-key on the keyboard

Check what is assigned to Print.

**Closed by tsujan** 2022-03-14 07:24 UTC

**Comment by ralf3u** [comment] 2022-03-14 08:53
>Check what is assigned to Print.

I looked for "print" in the document rc.xml that is located in .config/openbox, but the phrase could not be found.
I tried in the terminal this line:
xev | sed -ne '/^KeyPress/,/^$/p'
But if I press the print-key, then ScreenGrab appears, so I don't get a message in the terminal.

How do I get information about what is assigned to Print?
Thank you in advance for an answer.

**Comment by ralf3u** [comment] 2022-03-14 09:29
>Check what is assigned to Print.

In the global configuration "Print" is assigned to "screen shot" that is activated. The order there is "screengrab".

**Comment by ralf3u** [comment] 2022-06-07 12:53
@tsujan
>Not reproducible.

That's not true.
I did exactly the steps of the report, but this time in ScreenGrab 2.4.0 (using Qt 5.15.3), in Lubuntu 22.04 with LXQt 1.1.0.
In `Global Actions Manager` the shortcut `Print` is activated, is assigned to `screen shot`, and the command is `screengrab`.
For me it looks like a bug. Could you please reopen the issue and add the bug-label? Thank you in advance for an answer.

**Comment by tsujan** [comment] 2022-06-07 13:35
@ralf3u 
I can't reproduce this particular issue. Pressing `Print` or entering `screengrab` in a terminal results in a full-screen screenshot at step 8.

However, if `Options → Advanced → Allow multiple instances of ScreenGrab` is unchecked, what you see is most probably related to https://github.com/lxqt/screengrab/issues/184. If you press `Print` while ScreenGrab is running, the single-instance code of ScreenGrab will be called, and we know that it's buggy. I can reproduce various kinds of problems related to it; https://github.com/lxqt/screengrab/issues/184 was just one example.

Until that code is fixed, please use the "New" button or its shortcut `Ctrl+N` for taking several screenshots *if you don't want to exit ScreenGrab after taking each*.

**Comment by ralf3u** [comment] 2022-06-07 14:06
Personally, I'm not interested in "Allow multiple instances of ScreenGrab", but I just want to mention this:

Options → Advanced → Allow multiple instances of ScreenGrab
Checked or unchecked: It is reproducible for me in both cases.
Also with pressing `Print` or entering `screengrab` in a terminal.
